system:
  name: "xbd-dataset"
  subfolder_name: "xbd"
  local_dir: "data"
  kaggle_username: "qianlanzz"

folders:
  images: "images"
  labels: "labels"
  masks: "masks"

naming:
  pre_suffix: "_pre_disaster"
  post_suffix: "_post_disaster"
  pre_target_suffix: "_pre_disaster_target"
  post_target_suffix: "_post_disaster_target"
  extension: ".png"

train:
  dir: "tier1"

test:
  dir: "test"

stats:
# In RGB order
  mean: 
  - 0.3085
  - 0.3404
  - 0.2548
  std:
  - 0.1623
  - 0.1440
  - 0.1354

item_group:
  pre_image: "image"
  post_image: "post_image"
  pre_image_target: "pre_image_target"
  post_image_target: "post_image_target"